app:
  name: Monsoon Framework from Web context
  profiles:
    active: dev

server:
  port: 8080
  host: localhost

monsoon:
  datasource:
    enabled: true
    url: test
    username: test-username
    password: test-password
    driver: test-driver