app:
  name: Monsoon Framework from Web context
  profiles:
    active: dev

server:
  port: 8080
  host: localhost

monsoon:
  datasource:
    enabled: true
    driver: org.sqlite.JDBC
    url: jdbc:sqlite:test.db
    username: root
    password: root