app:
  name: Monsoon Framework from Web context
  profiles:
    active: dev

server:
  port: 8080
  host: localhost

monsoon:
  datasource:
    enabled: true
    driver: org.sqlite.JDBC
    database: test.db
    path:
    url: jdbc:sqlite
    username: root
    password: root
    enforceForeignKeys: true