app:
  profiles:
    active: dev

db:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:test.db
  username: root
  password: root

server:
  host: localhost
  port: 8080
  ssl:
    enabled: true
    keyStore: mykeystore.jks

servers:
  - host: localhost
    port: 8080
  - host: 192.168.1.10
    port: 9090